<?php
// Automatically Generated by TestLink Installer - Tue, 12 Jan 16 08:30:06 +0100
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'root');
define('DB_HOST', '127.0.0.1');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
